services:
  app:
    image: trendio-back
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://trendioDB:5432/trendio
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_ENDPOINT: http://minio:9000
    depends_on:
      - db
      - minio
    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: trendioDB
    environment:
      POSTGRES_DB: trendio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"      # Порт для доступа к API/веб-интерфейсу
      - "9001:9001"      # Порт для консоли управления
    environment:
      - MINIO_ROOT_USER=minioadmin      # Замените на ваше имя пользователя
      - MINIO_ROOT_PASSWORD=minioadmin   # Замените на ваш пароль
    volumes:
      - minio_data:/data  # Том для хранения данных
    command: server /data --console-address :9001

volumes:
  minio_data: