token:
  signing:
    key: basebasebasebasebasebasebasebasebasebasebasebasebasebasebasebase
spring:
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
  hibernate:
    dialect: org.hibernate.dialect.PostgreSQL14Dialect
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/trendio
    driverClassName: org.postgresql.Driver
    password: 'postgres'
  application:
    name: trendio
  jpa:
    hibernate:
      ddl-auto: validate
log4j:
  appender:
    FILE:
      encoding: UTF-8