token:
  signing:
    key: basebasebasebasebasebasebasebasebasebasebasebasebasebasebasebase
spring:
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
  hibernate:
    dialect: org.hibernate.dialect.PostgreSQL14Dialect
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/trendio
    driverClassName: org.postgresql.Driver
    password: 'postgres'
  application:
    name: trendio
  jpa:
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  kafka:
    bootstrap-servers: localhost:29092
#    properties:
#      hibernate:
#        show_sql: true

topic:
  name: user_actions

log4j:
  appender:
    FILE:
      encoding: UTF-8

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS-KEY:minioadmin}
  secret-key: ${MINIO_SECRET-KEY:minioadmin}
  bucket: avatars

comments:
  type: flat

service:
  name: trendioBack