CREATE SEQUENCE IF NOT EXISTS users_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE comments
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    request_id  BIGINT                                  NOT NULL,
    create_date TIMESTAMP WITHOUT TIME ZONE,
    update_date TIMESTAMP WITHOUT TIME ZONE,
    username    VARCHAR(255),
    text        VARCHAR(255),
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

CREATE TABLE images
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_url VARCHAR(255),
    CONSTRAINT pk_images PRIMARY KEY (id)
);

CREATE TABLE likes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_date TIMESTAMP WITHOUT TIME ZONE,
    user_id     BIGINT                                  NOT NULL,
    request_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_likes PRIMARY KEY (id)
);

CREATE TABLE passwords
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    password VARCHAR(255),
    CONSTRAINT pk_passwords PRIMARY KEY (id)
);

CREATE TABLE requests
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    address        VARCHAR(255),
    create_date    TIMESTAMP WITHOUT TIME ZONE,
    latitude       DOUBLE PRECISION                        NOT NULL,
    longitude      DOUBLE PRECISION                        NOT NULL,
    header_request VARCHAR(255),
    text_request   VARCHAR(255),
    CONSTRAINT pk_requests PRIMARY KEY (id)
);

CREATE TABLE requests_tags
(
    request_id BIGINT NOT NULL,
    tag_id     BIGINT NOT NULL
);

CREATE TABLE tags
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_tag VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id)
);

CREATE TABLE users
(
    id          BIGINT  NOT NULL,
    username    VARCHAR(255),
    enabled     BOOLEAN NOT NULL,
    role        VARCHAR(255),
    password_id BIGINT,
    avatar_id   BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE likes
    ADD CONSTRAINT uc_268491b9cbb4dba2c4a6ae2bf UNIQUE (user_id, request_id);

ALTER TABLE tags
    ADD CONSTRAINT uc_tags_name_tag UNIQUE (name_tag);

ALTER TABLE users
    ADD CONSTRAINT uc_users_avatar UNIQUE (avatar_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_password UNIQUE (password_id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_REQUEST FOREIGN KEY (request_id) REFERENCES requests (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE likes
    ADD CONSTRAINT FK_LIKES_ON_REQUEST FOREIGN KEY (request_id) REFERENCES requests (id);

ALTER TABLE likes
    ADD CONSTRAINT FK_LIKES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE requests
    ADD CONSTRAINT FK_REQUESTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_AVATAR FOREIGN KEY (avatar_id) REFERENCES images (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_PASSWORD FOREIGN KEY (password_id) REFERENCES passwords (id);

ALTER TABLE requests_tags
    ADD CONSTRAINT fk_reqtag_on_request_entity FOREIGN KEY (request_id) REFERENCES requests (id);

ALTER TABLE requests_tags
    ADD CONSTRAINT fk_reqtag_on_tag_entity FOREIGN KEY (tag_id) REFERENCES tags (id);