CREATE SEQUENCE IF NOT EXISTS users_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE comments
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comments_user    BIGINT,
    comments_request BIGINT,
    create_date      TIMESTAMP WITHOUT TIME ZONE,
    update_date      TIMESTAMP WITHOUT TIME ZONE,
    text             VARCHAR(255),
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

CREATE TABLE images
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_url VARCHAR(255),
    CONSTRAINT pk_images PRIMARY KEY (id)
);

CREATE TABLE likes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    create_date TIMESTAMP WITHOUT TIME ZONE,
    user_id     BIGINT                                  NOT NULL,
    request_id  BIGINT                                  NOT NULL,
    likes_users BIGINT,
    CONSTRAINT pk_likes PRIMARY KEY (id)
);

CREATE TABLE passwords
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    password VARCHAR(255),
    CONSTRAINT pk_passwords PRIMARY KEY (id)
);

CREATE TABLE requests
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requests_user  BIGINT                                  NOT NULL,
    address        VARCHAR(255),
    create_date    TIMESTAMP WITHOUT TIME ZONE,
    latitude       DECIMAL,
    longitude      DECIMAL,
    header_request VARCHAR(255),
    text_request   VARCHAR(255),
    CONSTRAINT pk_requests PRIMARY KEY (id)
);

CREATE TABLE requests_comments
(
    request_entity_id BIGINT NOT NULL,
    comments_id       BIGINT NOT NULL
);

CREATE TABLE requests_likes
(
    request_entity_id BIGINT NOT NULL,
    likes_id          BIGINT NOT NULL
);

CREATE TABLE requests_tags
(
    request_id BIGINT NOT NULL,
    tag_id     BIGINT NOT NULL
);

CREATE TABLE requests_user
(
    user_entity_id BIGINT NOT NULL,
    requests_id    BIGINT NOT NULL
);

CREATE TABLE tags
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_tag VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id)
);

CREATE TABLE users
(
    id          BIGINT  NOT NULL,
    username    VARCHAR(255),
    enabled     BOOLEAN NOT NULL,
    role        VARCHAR(255),
    password_id BIGINT,
    avatar_id   BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE likes
    ADD CONSTRAINT uc_268491b9cbb4dba2c4a6ae2bf UNIQUE (user_id, request_id);

ALTER TABLE requests_comments
    ADD CONSTRAINT uc_requests_comments_comments UNIQUE (comments_id);

ALTER TABLE requests_likes
    ADD CONSTRAINT uc_requests_likes_likes UNIQUE (likes_id);

ALTER TABLE requests_user
    ADD CONSTRAINT uc_requests_user_requests UNIQUE (requests_id);

ALTER TABLE tags
    ADD CONSTRAINT uc_tags_name_tag UNIQUE (name_tag);

ALTER TABLE users
    ADD CONSTRAINT uc_users_avatar UNIQUE (avatar_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_password UNIQUE (password_id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_COMMENTS_REQUEST FOREIGN KEY (comments_request) REFERENCES requests (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_COMMENTS_USER FOREIGN KEY (comments_user) REFERENCES users (id);

ALTER TABLE likes
    ADD CONSTRAINT FK_LIKES_ON_LIKES_USERS FOREIGN KEY (likes_users) REFERENCES users (id);

ALTER TABLE likes
    ADD CONSTRAINT FK_LIKES_ON_REQUEST FOREIGN KEY (request_id) REFERENCES requests (id);

ALTER TABLE likes
    ADD CONSTRAINT FK_LIKES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE requests
    ADD CONSTRAINT FK_REQUESTS_ON_REQUESTS_USER FOREIGN KEY (requests_user) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_AVATAR FOREIGN KEY (avatar_id) REFERENCES images (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_PASSWORD FOREIGN KEY (password_id) REFERENCES passwords (id);

ALTER TABLE requests_comments
    ADD CONSTRAINT fk_reqcom_on_comment_entity FOREIGN KEY (comments_id) REFERENCES comments (id);

ALTER TABLE requests_comments
    ADD CONSTRAINT fk_reqcom_on_request_entity FOREIGN KEY (request_entity_id) REFERENCES requests (id);

ALTER TABLE requests_likes
    ADD CONSTRAINT fk_reqlik_on_like_entity FOREIGN KEY (likes_id) REFERENCES likes (id);

ALTER TABLE requests_likes
    ADD CONSTRAINT fk_reqlik_on_request_entity FOREIGN KEY (request_entity_id) REFERENCES requests (id);

ALTER TABLE requests_tags
    ADD CONSTRAINT fk_reqtag_on_request_entity FOREIGN KEY (tag_id) REFERENCES requests (id);

ALTER TABLE requests_tags
    ADD CONSTRAINT fk_reqtag_on_tag_entity FOREIGN KEY (request_id) REFERENCES tags (id);

ALTER TABLE requests_user
    ADD CONSTRAINT fk_requse_on_request_entity FOREIGN KEY (requests_id) REFERENCES requests (id);

ALTER TABLE requests_user
    ADD CONSTRAINT fk_requse_on_user_entity FOREIGN KEY (user_entity_id) REFERENCES users (id);